# Generated by Django 5.2.7 on 2025-11-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRADA', 'Retirada')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_type_from', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Conta Poupança'), ('INVESTIMENTO', 'Conta Investimento')], max_length=20)),
                ('account_type_to', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Conta Poupança'), ('INVESTIMENTO', 'Conta Investimento')], max_length=20)),
                ('date', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='accounts.account')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='accounts.account')),
            ],
        ),
    ]
